name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Proto Build
     # working-directory: ./proto
      run: protoc --go_out=proto/ --go-grpc_out=require_unimplemented_servers=false:. ./proto/*.proto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
