name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Installing protoc-gen-go
      run: |
        go get -u google.golang.org/protobuf/cmd/protoc-gen-go
        go install google.golang.org/protobuf/cmd/protoc-gen-go
        go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
        export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Proto
      run: protoc --go_out=./proto --go-grpc_out=require_unimplemented_servers=false:./proto   ./proto/*.proto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
      version: "2022.1.1"
