name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install Buf
      uses: wizhi/setup-buf@v1

    - name: Installing protoc-gen-go
      run: |
        go get github.com/golang/protobuf/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc 

    - name: Proto Build
      run: protoc -I=$PROTO_DIR --go-grpc_out=$PROTO_DIR $(find $PROTO_DIR -type f -name '*.proto')
      env:
        PROTO_DIR: proto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
